# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
cd() { builtin cd "$@" && ls; }

PATH=$PATH:$HOME/Programs/Unix/Scripts
export PATH
